### PR TITLE
be verbose with git commands

### PR DESCRIPTION
**Pull request by dpickett**
as discussed in https://github.com/railsbridge-boston/railsbridge-boston/issues/11

### CODE REVIEW

**Comment by slothbear** [comment]
Thank you!

I have a question and an issue. Q) Should the status command be included? Its only purpose is for operation of the script (to stop if there's nothing to do).

I) @danchoi recommended the [multi-argument form for commit](https://github.com/railsbridge-boston/railsbridge-boston/issues/11#issuecomment-13031707) to make sure user input is properly escaped.

**Comment by danchoi** [comment]
@slothbear You needn't use the multi-argument form of `system()` if you won't be injecting any user input, whether from human or Klingon.

**Comment by slothbear** [comment]
git commit uses the message entered by the user. Klingon input. Now there's a visual.

**Comment by dpickett** [comment]
I'm indifferent about the status command - I think it's useful to see as much verbose output as possible but I can be convinced otherwise. 

For the context of the course, I'm not sure we need to worry about getting too crazy - we could escape single quotes, gsub them, or something like that

It's totally up to you - let me know what you'd like and I'll make it so :smiley:

**Comment by slothbear** [comment]
Thanks for your help -- much appreciated.

I agree with you on the status command; keep it.

For the commit message, the multi-argument form of the #system method will do all the work. Revert to this format: `system('git', 'commit', '--message', message)`

If I understood other-Dan and the doc, the single-argument form passes the command through the standard shell. A single quote (for instance) will cause the command to fail. The multi-argument form is not passed to the shell.

``` text
message = "I'm a lucky commit"
system('echo', message)
puts '---'
system("echo #{message}")
```

output

``` text
I'm a lucky commit
---
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by dpickett** [comment]
I think I've resolved what you're mentioning - output wise I did not escape or quote the message in the puts.

**Pull request merged**
